// Auto-generated by URP Connector — EmacEArt
// Runs once when this package is imported into a new project.
using System.IO;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEditor.PackageManager.Requests;
using UnityEngine;
using UnityEngine.Rendering;

[InitializeOnLoad]
public static class EA_19thCenturyCourtyards_ProjectSetup
{
    private const string PIPELINE_ASSET_PATH = "Assets/EmaceArt/19th Century Courtyards/Post Processing_profile/Settings/New Universal Render Pipeline Asset-HighQuality.asset";
    private const string URP_PACKAGE_ID      = "com.unity.render-pipelines.universal";
    // SessionState przeżyje recompile — po instalacji URP nie pytamy ponownie.
    private const string CONSENT_KEY         = "EA_19thCenturyCourtyards_ProjectSetup_Consented";

    private static AddRequest _urpAddRequest;
    private static ListRequest _urpListRequest;

    // Sprawdza RZECZYWISTY stan projektu — czy pipeline + color space są już ustawione.
    private static bool IsAlreadyConfigured()
    {
        var pipeline = AssetDatabase.LoadAssetAtPath<RenderPipelineAsset>(PIPELINE_ASSET_PATH);
        if (pipeline == null) return false;
        if (GraphicsSettings.defaultRenderPipeline != pipeline) return false;
        if (PlayerSettings.colorSpace != ColorSpace.Gamma) return false;
        return true;
    }

    // Wykrywa czy to projekt deweloperski Filipa (ma podpiętą paczkę UPM Editor_Cloude).
    // Jeśli tak — ProjectSetup MILCZY, nie ruszy nic w projekcie. Tylko czysty projekt
    // klienta (bez Editor_Cloude) widzi setup aktywny.
    private static bool IsDevProject()
    {
        try
        {
            string manifest = Path.Combine(
                Path.GetDirectoryName(Application.dataPath), "Packages", "manifest.json");
            if (!File.Exists(manifest)) return false;
            string text = File.ReadAllText(manifest);
            return text.IndexOf("com.emaceart.editor-cloude", System.StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("editor-cloude", System.StringComparison.OrdinalIgnoreCase) >= 0
                || text.IndexOf("Editor_Cloude", System.StringComparison.OrdinalIgnoreCase) >= 0;
        }
        catch { return false; }
    }

    static EA_19thCenturyCourtyards_ProjectSetup()
    {
        if (IsDevProject()) return;     // nie odpalamy w projekcie źródłowym Filipa
        EditorApplication.delayCall += TryRunSetup;
    }

    private static void TryRunSetup()
    {
        if (EditorApplication.isCompiling || EditorApplication.isUpdating)
        {
            EditorApplication.delayCall += TryRunSetup;
            return;
        }
        if (!UnityEditorInternal.InternalEditorUtility.isApplicationActive)
        {
            EditorApplication.delayCall += TryRunSetup;
            return;
        }
        if (IsAlreadyConfigured()) return;
        RunSetup();
    }

    private static void RunSetup()
    {
        if (IsAlreadyConfigured()) return;

        // Najpierw sprawdź czy paczka URP jest — bez niej shadery i tak nie skompilują się.
        // Lista paczek jest asynchroniczna; jeśli jeszcze nie odpowiedziała, poczekaj i wróć.
        if (_urpListRequest == null) _urpListRequest = Client.List(true);
        if (!_urpListRequest.IsCompleted)
        {
            EditorApplication.delayCall += TryRunSetup;
            return;
        }

        bool urpInstalled = false;
        if (_urpListRequest.Status == StatusCode.Success)
        {
            foreach (var p in _urpListRequest.Result)
                if (p.name == URP_PACKAGE_ID) { urpInstalled = true; break; }
        }

        // Jeśli user wcześniej kliknął Apply (przed instalacją URP + recompile),
        // nie pytamy ponownie — od razu kontynuujemy konfigurację.
        bool alreadyConsented = SessionState.GetBool(CONSENT_KEY, false);

        if (!alreadyConsented)
        {
            string dialogMsg =
                "One-click setup for 19th Century Courtyards.\n\n" +
                "This will configure your project so the asset\n" +
                "looks exactly as designed:\n\n" +
                (urpInstalled ? "" : "• Install Universal Render Pipeline package\n") +
                "• Color rendering → Gamma (recommended)\n" +
                "• Lighting calibrated for this asset\n" +
                "• Render Pipeline assigned to Graphics + all Quality levels\n\n" +
                "You can undo this at any time in Project Settings.";

            bool ok = EditorUtility.DisplayDialog(
                "19th Century Courtyards — Project Setup", dialogMsg, "Apply", "Skip");
            if (!ok) return;

            SessionState.SetBool(CONSENT_KEY, true);
        }

        if (!urpInstalled)
        {
            _urpAddRequest = Client.Add(URP_PACKAGE_ID);
            EditorApplication.update += WaitForUrpInstall;
            return;
        }

        ApplyPipelineAndSettings();
    }

    private static void WaitForUrpInstall()
    {
        if (_urpAddRequest == null || !_urpAddRequest.IsCompleted) return;
        EditorApplication.update -= WaitForUrpInstall;
        if (_urpAddRequest.Status == StatusCode.Success)
            Debug.Log($"[19th Century Courtyards] URP package installed: " + _urpAddRequest.Result.packageId);
        else
            Debug.LogError($"[19th Century Courtyards] URP package install FAILED: " + _urpAddRequest.Error?.message);
        // Po recompile InitializeOnLoad odpali ponownie, dokończy konfigurację.
        _urpAddRequest = null;
    }

    private static void ApplyPipelineAndSettings()
    {
        PlayerSettings.colorSpace = ColorSpace.Gamma;
        GraphicsSettings.lightsUseLinearIntensity = false;

        var pipeline = AssetDatabase.LoadAssetAtPath<RenderPipelineAsset>(PIPELINE_ASSET_PATH);
        if (pipeline != null)
        {
            // Assign to Graphics Settings
            GraphicsSettings.defaultRenderPipeline = pipeline;

            // Assign to all Quality levels
            int saved = QualitySettings.GetQualityLevel();
            for (int i = 0; i < QualitySettings.names.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                QualitySettings.renderPipeline = pipeline;
            }
            QualitySettings.SetQualityLevel(saved, false);

            // Quality tweaks — LOD podwyższone żeby wszystkie assety były widoczne na scenie
            for (int i = 0; i < QualitySettings.names.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                QualitySettings.lodBias = 30f;
                QualitySettings.terrainDetailDistance   = 200f;
                QualitySettings.terrainDetailDensityScale = 1.0f;
                QualitySettings.terrainMaxTrees          = 200;
            }
            QualitySettings.SetQualityLevel(saved, false);

            // Force save ProjectSettings
            EditorUtility.SetDirty(GraphicsSettings.GetGraphicsSettings());
            AssetDatabase.SaveAssets();
            Debug.Log($"[19th Century Courtyards] Pipeline assigned to Graphics + all Quality levels: {pipeline.name}");
        }
        else
        {
            Debug.LogWarning($"[19th Century Courtyards] Pipeline asset not found at: {PIPELINE_ASSET_PATH}");
        }

        // Fix known broken material GUIDs in this package
        FixMaterialGUIDs();

        // URP po instalacji generuje domyślny UniversalRenderPipelineGlobalSettings.asset
        // w Assets/. Paczka Filipa też ma swój (w Post Processing_profile/Settings/).
        // Usuwamy domyślny żeby aktywny był ten z paczki.
        RemoveDuplicateUrpGlobalSettings();

        // Podepnij TerrainData do wszystkich Terrain i TerrainCollider w scenach paczki
        AssignTerrainsInPackageScenes();

        // Wymuś reimport materiałów paczki — po świeżej instalacji URP shadery URP/Lit
        // czasem nie ładują się do materiałów dopóki ich nie ruszymy.
        ReimportPackageMaterials();

        Debug.Log($"[19th Century Courtyards] Project setup complete.");
        EditorUtility.DisplayDialog("19th Century Courtyards — Done",
            "Project configured successfully.\nYou can re-run setup from:\nTools → EmacEArt → 19th Century Courtyards Setup", "OK");
    }

    // Znajduje wszystkie UniversalRenderPipelineGlobalSettings.asset w projekcie.
    // Jeśli jest więcej niż jeden i jeden leży w paczce (/EmacEArt/ lub /EmaceArt/),
    // usuwa ten poza paczką — żeby aktywny był ten dostarczony z paczki.
    private static void RemoveDuplicateUrpGlobalSettings()
    {
        var guids = AssetDatabase.FindAssets("UniversalRenderPipelineGlobalSettings");
        if (guids == null || guids.Length <= 1) return;

        var paths = new System.Collections.Generic.List<string>();
        foreach (var g in guids)
        {
            string p = AssetDatabase.GUIDToAssetPath(g);
            if (p.EndsWith("UniversalRenderPipelineGlobalSettings.asset",
                System.StringComparison.OrdinalIgnoreCase))
                paths.Add(p);
        }
        if (paths.Count <= 1) return;

        string packageOne  = null;
        var toDelete = new System.Collections.Generic.List<string>();
        foreach (var p in paths)
        {
            if (p.Contains("/EmacEArt/") || p.Contains("/EmaceArt/")) packageOne = p;
            else toDelete.Add(p);
        }
        if (packageOne == null || toDelete.Count == 0) return;

        foreach (var p in toDelete)
        {
            if (AssetDatabase.DeleteAsset(p))
                Debug.Log($"[19th Century Courtyards] Removed duplicate URP Global Settings: " + p);
        }
        AssetDatabase.Refresh();
    }

    private static void AssignTerrainsInPackageScenes()
    {
        var tdGuids = AssetDatabase.FindAssets("t:TerrainData");
        if (tdGuids.Length == 0) return;

        // Force-reimport wszystkich TerrainData — naprawia broken cache
        // (jeśli wcześniejsza wersja paczki była uszkodzona).
        foreach (var g in tdGuids)
            AssetDatabase.ImportAsset(AssetDatabase.GUIDToAssetPath(g), ImportAssetOptions.ForceUpdate);
        AssetDatabase.Refresh();

        var terrainData = AssetDatabase.LoadAssetAtPath<TerrainData>(
            AssetDatabase.GUIDToAssetPath(tdGuids[0]));
        if (terrainData == null) return;

        var sceneGuids = AssetDatabase.FindAssets("t:Scene", new[] { "Assets" });
        var prevScene = UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene().path;
        bool anyFixed = false;

        foreach (var sg in sceneGuids)
        {
            string scenePath = AssetDatabase.GUIDToAssetPath(sg);
            if (!scenePath.Contains("/EmacEArt/") && !scenePath.Contains("/EmaceArt/")) continue;

            var scene = UnityEditor.SceneManagement.EditorSceneManager.OpenScene(
                scenePath, UnityEditor.SceneManagement.OpenSceneMode.Single);
            bool sceneDirty = false;
            foreach (var root in scene.GetRootGameObjects())
            {
                // BEZWARUNKOWE reassign — pokrywa też przypadki broken cache
                // gdzie referencja nie jest null ale Unity i tak pokazuje Missing.
                foreach (var t in root.GetComponentsInChildren<Terrain>(true))
                {
                    t.terrainData = terrainData;
                    sceneDirty = true;
                }
                foreach (var c in root.GetComponentsInChildren<TerrainCollider>(true))
                {
                    c.terrainData = terrainData;
                    sceneDirty = true;
                }
            }
            if (sceneDirty)
            {
                UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(scene);
                UnityEditor.SceneManagement.EditorSceneManager.SaveScene(scene);
                anyFixed = true;
            }
        }

        if (!string.IsNullOrEmpty(prevScene) && System.IO.File.Exists(prevScene))
            UnityEditor.SceneManagement.EditorSceneManager.OpenScene(
                prevScene, UnityEditor.SceneManagement.OpenSceneMode.Single);

        if (anyFixed) Debug.Log($"[19th Century Courtyards] Terrain references assigned across package scenes.");
    }

    private static void ReimportPackageMaterials()
    {
        var matGuids = AssetDatabase.FindAssets("t:Material", new[] { "Assets" });
        int reimported = 0;
        foreach (var g in matGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(g);
            if (!path.Contains("/EmacEArt/") && !path.Contains("/EmaceArt/")) continue;
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
            reimported++;
        }
        if (reimported > 0) Debug.Log($"[19th Century Courtyards] Reimported {reimported} package materials.");
    }

    private static void FixMaterialGUIDs()
    {
        // Fix stale GUID references — auto-generated by URP Connector (dynamic scan).
        // Keys are relative asset paths; values map old GUID → new GUID found by asset name.
        var fixes = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, string>>
        {
            // 19th_Material
            { "Assets/EmaceArt/19th Century Courtyards/Materials/19th_Material.mat", new System.Collections.Generic.Dictionary<string, string>
                {
                    { "d0353a89b1f911e48b9e16bdc9f2e058", FindGUID("AssetVersion", "texture") },
                    { "933532a4fcc9baf4fa0491de14d08ed7", FindGUID("Lit", "shader") },
                }
            },
            // EA_Cool Water
            { "Assets/EmaceArt/19th Century Courtyards/Materials/EA_Cool Water.mat", new System.Collections.Generic.Dictionary<string, string>
                {
                    { "d0353a89b1f911e48b9e16bdc9f2e058", FindGUID("AssetVersion", "texture") },
                }
            },
            // EA_Skybox
            { "Assets/EmaceArt/19th Century Courtyards/Materials/EA_Skybox.mat", new System.Collections.Generic.Dictionary<string, string>
                {
                    { "d0353a89b1f911e48b9e16bdc9f2e058", FindGUID("AssetVersion", "texture") },
                }
            },
            // Terrain_URP_Terrain
            { "Assets/EmaceArt/19th Century Courtyards/Terrain/Terrain_URP_Terrain.mat", new System.Collections.Generic.Dictionary<string, string>
                {
                    { "d0353a89b1f911e48b9e16bdc9f2e058", FindGUID("AssetVersion", "texture") },
                    { "69c1f799e772cb6438f56c23efccb782", FindGUID("TerrainLit", "shader") },
                }
            },

        };

        foreach (var kv in fixes)
        {
            // kv.Key is the relative asset path
            string path = kv.Key;
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string absPath = Path.Combine(projectRoot, path).Replace('\\', '/');
            if (!File.Exists(absPath)) continue;

            string content = System.IO.File.ReadAllText(absPath);
            bool dirty = false;
            foreach (var replace in kv.Value)
            {
                if (string.IsNullOrEmpty(replace.Value)) continue;
                if (content.Contains(replace.Key))
                {
                    content = content.Replace(replace.Key, replace.Value);
                    dirty = true;
                }
            }
            if (dirty)
            {
                System.IO.File.WriteAllText(absPath, content, System.Text.Encoding.UTF8);
                AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
                Debug.Log($"[19th Century Courtyards] Fixed material GUIDs: {System.IO.Path.GetFileNameWithoutExtension(path)}");
            }
        }
    }

    private static string FindGUID(string assetName, string type)
    {
        string filter = type == "shader" ? $"t:Shader {assetName}" : $"t:Texture {assetName}";
        string[] guids = AssetDatabase.FindAssets(filter);
        return guids.Length > 0 ? guids[0] : null;
    }

    [MenuItem("Tools/EmacEArt/19th Century Courtyards Setup")]
    public static void RunSetupManual()
    {
        _urpListRequest = null;     // wymuś świeże sprawdzenie URP
        RunSetup();
    }
}
